### PR TITLE
[DynamicBoneFix] Fix flexible gimmicks.

### LINKED ISSUE #76: KK_Fix_DynamicBones breaks some scenes after 22.0.0
it seems the rewrite mentioned in 22.0 version missed something. the characters in some scenes (ex. by Fujitsubo) will have their bones misaligned. here's some screenshots. 
how it used to be in 21.6 and with the dll disabled:
Image
and how it looks in 22.0:
Image

example card:
Image

### PR DESCRIPTION
**Pull request by Njaecha**
Fixes the "bug" breaking some scenes mentioned in https://github.com/IllusionMods/IllusionFixes/issues/76 by fixing the premature end of the dynamic bone chain as explained in my comment.

### CODE REVIEW

File: src/Core_Fix_DynamicBones/Core.DynamicBonesFix.cs [hunk 1]
```diff
@@ -17,6 +21,20 @@ public class DynamicBonesFix : BaseUnityPlugin
 
         internal static class Hooks
         {
+            #if KK || KKS
+            [HarmonyPostfix,  HarmonyPatch(typeof(Studio.AddObjectItem), nameof(Studio.AddObjectItem.Load), typeof(OIItemInfo), typeof(ObjectCtrlInfo), typeof(TreeNodeObject), typeof(bool), typeof(int))]
+            internal static void GimmickLoadPostfix(OCIItem __result, OIItemInfo _info)
+            {
+                // match flexible hanging gimmicks
+                if (_info.group != 10 || _info.category != 2 || !new List<int> { 393, 395, 492, 492 }.Contains(_info.no)) return;
```
Comment (ManlyMarco) [inline src/Core_Fix_DynamicBones/Core.DynamicBonesFix.cs]:
```suggestion
                if (_info.group != 10 || _info.category != 2) return;
                var no = _info.no
                if (no != 393 && no != 395 && no != 492 && no != 492) return;
```

File: src/Core_Fix_DynamicBones/Core.DynamicBonesFix.cs [hunk 2]
```diff
@@ -17,6 +21,22 @@ public class DynamicBonesFix : BaseUnityPlugin
 
         internal static class Hooks
         {
+            #if KK || KKS
+            [HarmonyPostfix,  HarmonyPatch(typeof(Studio.AddObjectItem), nameof(Studio.AddObjectItem.Load), typeof(OIItemInfo), typeof(ObjectCtrlInfo), typeof(TreeNodeObject), typeof(bool), typeof(int))]
```
Comment (ManlyMarco) [inline src/Core_Fix_DynamicBones/Core.DynamicBonesFix.cs:26]:
```suggestion
            // The game was abusing a bug in some gimmicks that got fixed by this plugin, so this changes the gimmicks to use the correct way to end the chain
            [HarmonyPostfix,  HarmonyPatch(typeof(Studio.AddObjectItem), nameof(Studio.AddObjectItem.Load), typeof(OIItemInfo), typeof(ObjectCtrlInfo), typeof(TreeNodeObject), typeof(bool), typeof(int))]
```

**Comment by Njaecha** [comment]
From Issue:
"The change to the fix I implemented had the core purpose of allowing multiple consecutive bones in the notRolls list since that would end the bonechain prematurely before. Ending the chain prematurely is done by adding the children of a bone to the Exclusions list. [...] However, the devs used the bug that makes a chain end by adding two consecutive bones to notRolls."

This PR intercepts the AddObjectItem.Load process and adds the "N_setuzoku" bone to the m_Exlcusions list and clears  the m_notRolls list. Like that the dynamic bone chain correctly ends on the gimmick again and does not continue into the item parented to it.

**Review by ManlyMarco — APPROVED** [review]
