### PR TITLE
[FixDynamicBones] Fix nipple rings

### LINKED ISSUE #80: KK_Fix_DynamicBones causes accessories bound to the nipple to be incorrectly positioned dynamically, such as nipple rings.
KK_Fix_DynamicBones causes accessories bound to the nipple to be incorrectly positioned dynamically, such as nipple rings.
It's in a very confusing position and won't lock onto the nipple.

### PR DESCRIPTION
**Pull request by Njaecha**
The game has a very weird structure for the dynamic bone on nipple rings which breaks if there is a leaf-particle on the chain.
Since this fix removed the issue that leaf particles will only be added for transforms without children, the EndLength and EndOffset parameters have to actually be 0 now.
Fixes https://github.com/IllusionMods/IllusionFixes/issues/80

### CODE REVIEW

File: src/Core_Fix_DynamicBones/Core.DynamicBonesFix.cs [hunk 1]
```diff
@@ -38,6 +40,32 @@ internal static void GimmickLoadPostfix(OCIItem __result, OIItemInfo _info)
             }
             #endif
             
+            #if KK || KKS
+            // The game has a very weird structure for the dynamic bone on nipple rings which breaks if there is a leaf-particle on the chain.
+            // Since this fix removed the issue that leaf particles will only be added for transforms without children,
+            // the EndLength and EndOffset parameters have to actually be 0 now.  
+            [HarmonyPostfix, HarmonyPatch(typeof(ChaControl), nameof(ChaControl.ChangeShakeAccessory))]
```
Comment (ManlyMarco) [inline src/Core_Fix_DynamicBones/Core.DynamicBonesFix.cs]:
```suggestion
            [HarmonyPostfix, HarmonyWrapSafe, HarmonyPatch(typeof(ChaControl), nameof(ChaControl.ChangeShakeAccessory))]
```

File: src/Core_Fix_DynamicBones/Core.DynamicBonesFix.cs [hunk 2]
```diff
@@ -38,6 +40,32 @@ internal static void GimmickLoadPostfix(OCIItem __result, OIItemInfo _info)
...
+            // the EndLength and EndOffset parameters have to actually be 0 now.  
+            [HarmonyPostfix, HarmonyWrapSafe, HarmonyPatch(typeof(ChaControl), nameof(ChaControl.ChangeShakeAccessory))]
+            internal static void NippleRingPostfix(int slotNo, ChaControl __instance)
+            {
+                ChaFileAccessory.PartsInfo accessoryPart = __instance.nowCoordinate.accessory.parts[slotNo];
+                if (accessoryPart.type != 125) return; // has to be a torso accessory
+                GameObject gameObject = __instance._objAccessory[slotNo];
+                DynamicBone dynamicBone = gameObject.GetComponentInChildren<DynamicBone>();
+                if (!dynamicBone || (dynamicBone.m_EndLength == 0 && dynamicBone.m_EndOffset == Vector3.zero)) return;
+                Transform yure1 = gameObject.transform.FindLoop("N_move").transform.Children().Find(t => t.name.Contains("yure"));
```
Comment (ManlyMarco) [inline src/Core_Fix_DynamicBones/Core.DynamicBonesFix.cs]:
```suggestion
                Transform yure1 = gameObject.transform.FindLoop("N_move")?.transform.Children().Find(t => t.name.Contains("yure"));
```

**Review by ManlyMarco — APPROVED** [review]
